import React, { useState } from 'react';
import { ImageUploader } from './components/ImageUploader';
import { AnalysisLoading } from './components/AnalysisLoading';
import { RepairGuideView } from './components/RepairGuideView';
import { analyzeRepairScenario, generateRepairImage, fileToGenerativePart } from './services/geminiService';
import { AppState, RepairGuide } from './types';
import { Wrench, Zap, FileText } from 'lucide-react';

const App: React.FC = () => {
  const [appState, setAppState] = useState<AppState>(AppState.IDLE);
  const [brokenImage, setBrokenImage] = useState<File | null>(null);
  const [scrapImage, setScrapImage] = useState<File | null>(null);
  const [brokenPreview, setBrokenPreview] = useState<string | null>(null);
  const [scrapPreview, setScrapPreview] = useState<string | null>(null);
  const [repairGuide, setRepairGuide] = useState<RepairGuide | null>(null);

  const handleBrokenImage = (file: File | null) => {
    setBrokenImage(file);
    setBrokenPreview(file ? URL.createObjectURL(file) : null);
  };

  const handleScrapImage = (file: File | null) => {
    setScrapImage(file);
    setScrapPreview(file ? URL.createObjectURL(file) : null);
  };

  const startAnalysis = async () => {
    if (!brokenImage || !scrapImage) return;

    setAppState(AppState.ANALYZING);
    try {
      // Step 1: Analyze text and structure using Gemini 3 Pro
      const guide = await analyzeRepairScenario(brokenImage, scrapImage);
      
      // Step 2: Start image generation in background for each step
      setRepairGuide(guide);
      setAppState(AppState.GENERATING_IMAGES);

      // Prepare reference image for generation (the broken object)
      const referenceBase64 = await fileToGenerativePart(brokenImage);

      // Map steps to image generation promises
      const updatedSteps = [...guide.steps];
      
      const imagePromises = updatedSteps.map(async (step, index) => {
        // Use the specific visualization prompt generated by Gemini 3
        // combined with the description for maximum context.
        const fullPrompt = `Show this specific repair action: ${step.title}. Visual details: ${step.visualizationPrompt || step.description}.`;
        
        const imageUrl = await generateRepairImage(fullPrompt, referenceBase64);
        updatedSteps[index] = { ...step, generatedImageUrl: imageUrl };
        
        // Update state progressively
        setRepairGuide(prev => prev ? ({ ...prev, steps: [...updatedSteps] }) : null);
      });

      await Promise.all(imagePromises);
      setAppState(AppState.READY);

    } catch (error) {
      console.error(error);
      setAppState(AppState.ERROR);
      alert("Something went wrong with the Jugaad Engineer. Please try again.");
      setAppState(AppState.IDLE);
    }
  };

  const resetApp = () => {
    setAppState(AppState.IDLE);
    setBrokenImage(null);
    setScrapImage(null);
    setBrokenPreview(null);
    setScrapPreview(null);
    setRepairGuide(null);
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-slate-900 to-slate-800 text-slate-100 selection:bg-amber-500/30">
      
      {appState === AppState.ANALYZING && <AnalysisLoading />}

      <nav className="border-b border-slate-800 bg-slate-900/50 backdrop-blur-md sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-amber-500 rounded-lg flex items-center justify-center">
              <Wrench size={18} className="text-slate-900" />
            </div>
            <span className="font-display font-bold text-xl tracking-tight">The Jugaad Engineer</span>
          </div>
          <div className="text-xs font-mono text-slate-500 hidden sm:block">
            HACKATHON 2026 • CONCEPT PROTOTYPE
          </div>
        </div>
      </nav>

      <main className="p-4 md:p-8">
        {(appState === AppState.IDLE || appState === AppState.ERROR) && (
          <div className="max-w-4xl mx-auto pt-8 md:pt-16 animate-fadeIn">
            <div className="text-center mb-12 space-y-4">
              <h1 className="text-5xl md:text-6xl font-bold font-display leading-tight">
                Broken Essential? <br/>
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 to-orange-500">Fix it with Junk.</span>
              </h1>
              <p className="text-xl text-slate-400 max-w-2xl mx-auto">
                Upload a photo of your broken machinery and your available scrap pile. 
                Our AI structural engineer will generate a physics-valid repair guide.
              </p>
            </div>

            <div className="grid md:grid-cols-2 gap-6 bg-slate-800/50 p-6 md:p-8 rounded-2xl border border-slate-700/50 shadow-2xl">
              <ImageUploader 
                label="The Broken Object" 
                description="Upload a clear photo of the damage."
                onImageSelected={handleBrokenImage}
                previewUrl={brokenPreview}
              />
              <ImageUploader 
                label="The Scrap Pile" 
                description="Upload a photo of available trash/materials."
                onImageSelected={handleScrapImage}
                previewUrl={scrapPreview}
              />
            </div>

            <div className="mt-8 flex justify-center">
              <button
                onClick={startAnalysis}
                disabled={!brokenImage || !scrapImage}
                className={`
                  relative overflow-hidden group px-8 py-5 rounded-xl font-bold text-lg transition-all duration-300 flex items-center gap-3
                  ${(!brokenImage || !scrapImage) 
                    ? 'bg-slate-800 text-slate-500 cursor-not-allowed' 
                    : 'bg-gradient-to-r from-amber-500 to-orange-600 text-white shadow-lg shadow-orange-500/20 hover:shadow-orange-500/40 hover:scale-105'
                  }
                `}
              >
                <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                <Zap size={20} className={(!brokenImage || !scrapImage) ? '' : 'fill-current'} />
                <span>Generate Repair Plan</span>
              </button>
            </div>
            
            <div className="mt-16 grid grid-cols-3 gap-4 text-center opacity-50">
               <div>
                  <div className="font-bold text-slate-300 mb-1">Gemini 3 Pro</div>
                  <div className="text-sm">Analyzes physics & failure points</div>
               </div>
               <div>
                  <div className="font-bold text-slate-300 mb-1">Gemini 2.5 Flash</div>
                  <div className="text-sm">Instantly visualizes repair steps</div>
               </div>
               <div>
                  <div className="font-bold text-slate-300 mb-1">Context Aware</div>
                  <div className="text-sm">Sees your actual broken object</div>
               </div>
            </div>
          </div>
        )}

        {(appState === AppState.GENERATING_IMAGES || appState === AppState.READY) && repairGuide && (
           <RepairGuideView guide={repairGuide} onReset={resetApp} />
        )}
      </main>

      <style>{`
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .animate-fadeIn {
          animation: fadeIn 0.6s ease-out forwards;
        }
      `}</style>
    </div>
  );
};

export default App;